Playlist.Zone.Administration/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Playlist.Zone.Dto.Music.Charts;
using Playlist.Zone.Dto.Music.Playlist;
using Playlist.Zone.Datatier.Music.Charts;
using Playlist.Zone.Datatier.Music.Playlists;
using Playlist.Zone.Services.Music.Charts.ChartParser;
using Playlist.Zone.Services.Music.Charts.ChartParser.YoutubeParser;
using Playlist.Zone.Services.Music.Charts.ChartParser.iTunesParser;
using Playlist.Zone.Services.Music.External;
using Playlist.Zone.Music.Charts.ChartBuilderService;
using Playlist.Zone.Services.Music.Charts.ChartBuilderService;
using Playlist.Zone.Administration.Code.Settings;
using Playlist.Zone.Services.Music.Charts.ChartParser.ShazamParser;
using Playlist.Zone.Music.Charts.ChartParser.BillboardParser;
using Compiler.Utility.Settings;

namespace Playlist.Zone.Administration.Controllers
{
    [Authorize(Roles="Admin")]
    public class MusicController : Controller
    {
        
        protected readonly IChartEntity _chartManager;
        protected readonly IPlaylistEntity _playlistManager;
        protected readonly IBaseSettings _currSettings;
        protected readonly ISearchMusicService _youtubeSearchService;

        public MusicController(
            IChartEntity pChartManager,
            IBaseSettings pCurrSettings, 
            ISearchMusicService pYoutubeSearchService,
            IPlaylistEntity pPlaylistManager)
        {
            _chartManager = pChartManager;
            _currSettings = pCurrSettings;
            _youtubeSearchService = pYoutubeSearchService;
            _playlistManager = pPlaylistManager;
        }




        public IActionResult Index()
        {
            return View();
        }


        public async Task<ActionResult> Charts()
        {
            List<AbstractChartDto> chartList = new List<AbstractChartDto>();
            chartList = await _chartManager.GetRecent();
            return View(chartList);
        }


        public async Task<ActionResult> Playlists()
        {
            IEnumerable<AbstractPlaylistDto> retObj;
            retObj = await _playlistManager.GetAll();
            return View(retObj);
        }



        public async Task<ActionResult> Generate(int Id)
        {
            Compiler.Common.Music.ChartType ChartType = (Compiler.Common.Music.ChartType)Id;

            IChartSongEntity chartSongManager = new ChartSongEntity(_currSettings);
            IChartEntity dbChartManager = new ChartEntity(chartSongManager, _currSettings);
            IChartBuilderService chartBuilderService = new ChartBuilderService(dbChartManager, _youtubeSearchService);

            List<System.Collections.Generic.KeyValuePair<string, string>> headers_list = new List<KeyValuePair<string, string>>();
            headers_list.Add(new KeyValuePair<string, string>("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"));
            headers_list.Add(new KeyValuePair<string, string>("upgrade-insecure-requests", "1"));
            headers_list.Add(new KeyValuePair<string, string>("accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,* / *;q=0.8"));
            headers_list.Add(new KeyValuePair<string, string>("accept-language", "en-US,en;q=0.9"));
            headers_list.Add(new KeyValuePair<string, string>("cache-control", "max-age=0"));
            headers_list.Add(new KeyValuePair<string, string>("Proxy-Connection", "keep-alive"));
            
            AbstractChartDto currChart = new ChartDto();

            switch (ChartType)
            {
                case Compiler.Common.Music.ChartType.Shazam:
                    {
                        headers_list.Add(new KeyValuePair<string, string>("authority", "www.shazam.com"));
                        headers_list.Add(new KeyValuePair<string, string>("method", "GET"));
                        headers_list.Add(new KeyValuePair<string, string>("path", "/shazam/v2/en-US/US/web/-/tracks/web_chart_us"));
                        headers_list.Add(new KeyValuePair<string, string>("scheme", "https"));
                        IChartParser shazamParser = new ShazamParser();
                        currChart = await chartBuilderService.BuildChart("https://www.shazam.com/shazam/v2/en-US/US/web/-/tracks/web_chart_us", headers_list, shazamParser);
                    }
                    break;
                case Compiler.Common.Music.ChartType.Billboard:
                    {
                        headers_list.Add(new KeyValuePair<string, string>("Referer", "http://www.billboard.com/charts"));
                        IChartParser billboardParser = new BillboardParser();
                        currChart = await chartBuilderService.BuildChart("http://www.billboard.com/charts/hot-100", headers_list, billboardParser);
                    }
                    break;
                case Compiler.Common.Music.ChartType.iTunes:
                    {
                        headers_list.Add(new KeyValuePair<string, string>("Referer", "https://www.apple.com/itunes/charts/"));
                        IChartParser ichartParser = new iTunesParser();
                        currChart = await chartBuilderService.BuildChart("https://music.apple.com/us/playlist/top-100-usa/pl.606afcbb70264d2eb2b51d8dbcfa6a12", headers_list, ichartParser);
                    }
                    break;
                case Compiler.Common.Music.ChartType.YouTube:
                    {
                        IChartParser youtubeParser = new YoutubeParser();
                        currChart = await chartBuilderService.BuildChart("https://charts.youtube.com/charts/TopSongs/us ", headers_list, youtubeParser);
                    }
                    break;
                default:
                    break;
            }

            return Redirect("/Music/Charts");
        }



        
    }
}

Playlist.Zone.Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Playlist.Zone.Administration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <div style="float:left;">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Playlist.Zone Admin</a>
                </div>

                <div style="float:left;">

                    <div style="float:left;">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Index">Music</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                            </li>
                        </ul>
                    </div>


                </div>

                <div style="float:right;">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <partial name="~/Views/Shared/_LoginPartial.cshtml" />
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Playlist.Zone.Administration - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Playlist.Zone.Administration/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Compiler Admin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet" />
    </environment>
</head>


<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Admin</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>

    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Admin</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>